version: '3.8'

services:
  personal-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-portfolio-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# Optional: Add volumes for development
# volumes:
#   portfolio-data:
#     driver: local